// <auto-generated />
namespace NewKLUE.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class timed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(timed));
        
        string IMigrationMetadata.Id
        {
            get { return "201810182311099_timed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
